import type { BrandAuditReport } from "@/lib/brand-audit/types";

export const SHIFTHUB_SAMPLE_REPORT: BrandAuditReport = {
  brandName: "Shifthub",
  brandUrl: "https://shifthub.io",
  isSampleData: true,
  generatedAt: new Date().toISOString(),
  scores: {
    seoScore: 78,
    technicalScore: 85,
    contentScore: 72,
    llmVisibilityScore: 15,
    overallHealthScore: 38,
  },
  websiteAudit: {
    url: "https://shifthub.io",
    scrapedAt: new Date().toISOString(),
    basic: {
      title: "Shifthub — Contact Centre Workforce Management",
      metaDescription: "Cloud WFM for contact centres. Shift scheduling, forecasting, and roster management.",
      metaKeywords: ["workforce management", "contact centre", "scheduling"],
      canonical: "https://shifthub.io",
      lang: "en",
    },
    seo: {
      h1Count: 1,
      h1Text: ["From Excel to Excellence"],
      h2Count: 4,
      h2Text: ["Transform Your Contact Centre", "Key Features", "Benefits", "Why Shifthub"],
      h3Count: 6,
      imageCount: 18,
      imagesWithoutAlt: 3,
      internalLinks: 24,
      externalLinks: 6,
      wordCount: 1240,
      hasSchemaMarkup: false,
      schemaTypes: [],
      hasSitemap: true,
      sitemapUrl: "https://shifthub.io/sitemap.xml",
      robotsMeta: "index, follow",
      isIndexable: true,
    },
    social: {
      hasOpenGraph: true,
      ogTitle: "Shifthub WFM",
      ogDescription: "Workforce management for contact centres",
      ogImage: "",
      hasTwitterCard: true,
      twitterCard: "summary_large_image",
    },
    technical: {
      isHttps: true,
      hasViewportMeta: true,
      hasCanonical: true,
      responseTimeMs: 1200,
      technologies: ["Google Analytics"],
      hasGoogleAnalytics: true,
      hasGTM: false,
      gtmId: "",
    },
    content: {
      headings: [
        { level: "h1", text: "From Excel to Excellence" },
        { level: "h2", text: "Transform Your Contact Centre" },
        { level: "h2", text: "Key Features" },
      ],
      mainKeywords: ["workforce", "scheduling", "contact", "centre", "roster"],
      hasContactInfo: true,
      hasPricingPage: false,
      hasBlogSection: false,
      ctaTexts: ["Book a Demo", "Contact Sales"],
    },
  },
  llmResults: [
    {
      brandName: "Shifthub",
      brandUrl: "https://shifthub.io",
      llmProvider: "openai",
      llmModel: "gpt-4o-mini",
      queryText: "What is Shifthub and what does it do?",
      queryCategory: "direct",
      brandMentioned: true,
      mentionPosition: 1,
      sentiment: "positive",
      exactQuote: "Shifthub is a workforce management platform focused on contact centres.",
      competitorsMentioned: [],
      fullResponse: "Shifthub is a workforce management platform focused on contact centres in Australia.",
      visibilityScore: 15,
      queriedAt: new Date().toISOString(),
    },
    {
      brandName: "Shifthub",
      brandUrl: "https://shifthub.io",
      llmProvider: "anthropic",
      llmModel: "claude-3-5-sonnet",
      queryText: "What are the best workforce management tools for call centres in 2024?",
      queryCategory: "category",
      brandMentioned: false,
      mentionPosition: null,
      sentiment: "not_mentioned",
      exactQuote: null,
      competitorsMentioned: ["Deputy", "When I Work", "7shifts"],
      fullResponse: "Top tools include Deputy, When I Work, and 7shifts for scheduling.",
      visibilityScore: 0,
      queriedAt: new Date().toISOString(),
    },
  ],
  competitorsFound: ["When I Work", "Deputy", "7shifts", "Shiftboard"],
  recommendations: [
    "Add Organization schema markup to improve AI visibility.",
    "Brand not mentioned in most category queries — publish comparison content vs Deputy and 7shifts.",
    "3 images missing alt text — add descriptive alt attributes.",
    "Consider a pricing page to capture commercial-intent queries.",
  ],
};

export const CIRCLE_HEALTHCARE_SAMPLE_REPORT: BrandAuditReport = {
  brandName: "Circle Healthcare",
  brandUrl: "https://circle.healthcare",
  isSampleData: true,
  generatedAt: new Date().toISOString(),
  scores: {
    seoScore: 82,
    technicalScore: 92,
    contentScore: 88,
    llmVisibilityScore: 32,
    overallHealthScore: 52,
  },
  websiteAudit: {
    url: "https://circle.healthcare",
    scrapedAt: new Date().toISOString(),
    basic: {
      title: "Circle Healthcare — AI-Powered Care Management",
      metaDescription: "CCM, RPM, BHI, PCM, and TCM for physician groups and ACOs. HIPAA compliant.",
      metaKeywords: ["chronic care management", "remote patient monitoring", "value-based care"],
      canonical: "https://circle.healthcare",
      lang: "en",
    },
    seo: {
      h1Count: 1,
      h1Text: ["AI-Powered Care Coordination"],
      h2Count: 5,
      h2Text: ["CCM Programs", "Remote Patient Monitoring", "Certifications", "For Practices", "Resources"],
      h3Count: 8,
      imageCount: 22,
      imagesWithoutAlt: 1,
      internalLinks: 31,
      externalLinks: 4,
      wordCount: 2100,
      hasSchemaMarkup: true,
      schemaTypes: ["Organization", "MedicalOrganization"],
      hasSitemap: true,
      sitemapUrl: "https://circle.healthcare/sitemap.xml",
      robotsMeta: "index, follow",
      isIndexable: true,
    },
    social: {
      hasOpenGraph: true,
      ogTitle: "Circle Healthcare",
      ogDescription: "Care management for value-based care",
      ogImage: "https://circle.healthcare/og.png",
      hasTwitterCard: true,
      twitterCard: "summary_large_image",
    },
    technical: {
      isHttps: true,
      hasViewportMeta: true,
      hasCanonical: true,
      responseTimeMs: 980,
      technologies: ["Next.js", "Google Tag Manager", "HubSpot"],
      hasGoogleAnalytics: false,
      hasGTM: true,
      gtmId: "GTM-NF2MMM2B",
    },
    content: {
      headings: [
        { level: "h1", text: "AI-Powered Care Coordination" },
        { level: "h2", text: "Chronic Care Management" },
      ],
      mainKeywords: ["care", "management", "patient", "chronic", "monitoring"],
      hasContactInfo: true,
      hasPricingPage: true,
      hasBlogSection: true,
      ctaTexts: ["Request Demo", "Learn More"],
    },
  },
  llmResults: [
    {
      brandName: "Circle Healthcare",
      brandUrl: "https://circle.healthcare",
      llmProvider: "openai",
      llmModel: "gpt-4o-mini",
      queryText: "What is Circle Healthcare and what services do they offer?",
      queryCategory: "direct",
      brandMentioned: true,
      mentionPosition: 1,
      sentiment: "positive",
      exactQuote: "Circle Healthcare offers CCM, RPM, and care coordination for physician groups.",
      competitorsMentioned: [],
      fullResponse: "Circle Healthcare offers CCM, RPM, BHI, and care coordination platforms.",
      visibilityScore: 15,
      queriedAt: new Date().toISOString(),
    },
    {
      brandName: "Circle Healthcare",
      brandUrl: "https://circle.healthcare",
      llmProvider: "perplexity",
      llmModel: "sonar",
      queryText: "Best chronic care management software for physician groups in 2024",
      queryCategory: "category",
      brandMentioned: true,
      mentionPosition: 3,
      sentiment: "neutral",
      exactQuote: "Circle Healthcare is among platforms serving physician groups.",
      competitorsMentioned: ["Welldoc", "Validic"],
      fullResponse: "Leading options include Welldoc, Validic, and Circle Healthcare for CCM.",
      visibilityScore: 11,
      queriedAt: new Date().toISOString(),
    },
  ],
  competitorsFound: ["Welldoc", "Validic", "Azara Healthcare"],
  recommendations: [
    "Strong technical foundation — maintain GTM and schema markup.",
    "Expand category-query content targeting ACO and RPM comparisons.",
    "Publish HIPAA/SOC 2 trust content to win enterprise LLM citations.",
  ],
};

export function getSampleReport(brandKey: string): BrandAuditReport | null {
  const key = brandKey.toLowerCase();
  if (key.includes("shift")) return SHIFTHUB_SAMPLE_REPORT;
  if (key.includes("circle")) return CIRCLE_HEALTHCARE_SAMPLE_REPORT;
  return null;
}
